### ISSUE TITLE
cant join any server

### ISSUE THREAD

**Issue by some-du6e** [2Retr0/ItemFavorites#5]
me when the Internal Exception: io.netty.handler.codec.DocoderException: net.minecraft.class_151: Non [a-z0-9/._-]
                                                                                                                                                                                      ^important
also i something about a nbt thing

logs are not important btw

**Comment by Soggy-Pancake** [comment]
I am also having this issue and the same error message. Minecraft is 1.20.2
![image](https://github.com/2Retr0/ItemFavorites/assets/54160598/dfedd430-7358-4f75-97c0-7b2e72af9b67)

**Comment by 2Retr0** [comment]
Turns out the favorite status NBT entry was still being added/sent to servers that were not using the mod; this caused a mismatch that resulted in the rejection. This issue has been fixed with the 1.0.5+1.20.1 release!
